baseURL = 'https://sartimo.github.io'
languageCode = 'en-us'
title = "timo sarkar's official web presence"
author = "sartimo"
copyright = "Â© 2019 - 2023 timo sarkar"
googleAnalytics = "G-CNQE23ECH5"

publishDir = "W:\\"

# ----- Site settings -----
theme = "risotto"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main" # Automatically add content sections to main menu
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser.attribute]
block = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# -----.Site.Params-----
[params]
noindex = false
source = "https://github.com/sartimo/sartimo.github.io"

[params.theme]
palette = "base16-dark-custom"

[params.about] # to be used only in about section of Sidebar
title = "sartimo"
description = "The online interspace and fediverse presence for timo sarkar"
logo = "avatars/BRZ (125x125).jpg"

# -----Sidebar: menu items-----
[menu] # Customize specific menu items
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"

    [[menu.main]]
    identifier = "heyo"
    name = "Heyo"
    url = "https://sartimo.github.io/hi"

# -----Sidebar: social links-----
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')
[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/sartimo"

[[params.socialLinks]]
icon = "fa-brands fa-twitter"
title = "X"
url = "https://x.com/timosar"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:sartimo10@gmail.com"

# -----Privacy Settings-----
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
  [privacy.mastodon]
    disable = false
    privacyEnhanced = false

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
